### ISSUE TITLE
Recreate Dropbox's reset password email

### ISSUE THREAD

**Issue by ribeiroevandro** [zenorocha/react-email-apps#31]
It's important that we try to recreate real emails in order to validate the quality and developer experience of our components. This is an example of a reset password email.

> Original: [Reset your Dropbox password.eml.zip](https://github.com/zenorocha/react-email/files/9642543/Reset.your.Dropbox.password.eml.zip)

![image](https://user-images.githubusercontent.com/943553/205548840-36a05caf-e939-4b6a-942f-44d2258d78da.png)

**Comment by zenorocha** [comment]
PR merged: https://github.com/zenorocha/react-email-apps/pull/32

Thanks @ribeiroevandro!
